[workspace]
resolver = "2"
members = [
    "crates/oxide-sql-core",
    "crates/oxide-sql-derive",
    "crates/oxide-sql-sqlite",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Danny Willems"]
license = "MIT"
repository = "https://github.com/leakix/oxide-sql"

[workspace.dependencies]
oxide-sql-core = { path = "crates/oxide-sql-core" }
oxide-sql-derive = { path = "crates/oxide-sql-derive" }
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
